export const ApiGatewayRequest = {
  from: <
    TBody extends Record<string, unknown>,
    THeaders extends Record<string, unknown>,
    TAuthorizer extends Record<string, unknown>,
    TPathParameters extends Record<string, unknown>,
  >(
    body: TBody,
    headers: THeaders,
    authorizer: TAuthorizer,
    pathParameters?: TPathParameters,
  ) => {
    return {
      body: { ...body },
      cookies: {},
      httpMethod: "POST",
      isBase64Encoded: false,
      multiValueHeaders: {},
      multiValueQueryStringParameters: {},
      pathParameters: pathParameters,
      path: "/",
      queryStringParameters: {},
      headers: {
        Accept: "application/json",
        Host: "1234567890.execute-api.us-east-1.amazonaws.com",
        "User-Agent": "Custom User Agent String",
        ...headers,
      },
      requestContext: {
        accountId: "",
        apiId: "",
        authorizer: {
          principalId: "",
          integrationLatency: 0,
          ...authorizer,
        },
        httpMethod: "POST",
        identity: {
          accessKey: null,
          accountId: null,
          apiKey: null,
          apiKeyId: null,
          caller: null,
          clientCert: null,
          cognitoAuthenticationProvider: null,
          cognitoAuthenticationType: null,
          cognitoIdentityId: null,
          cognitoIdentityPoolId: null,
          principalOrgId: null,
          sourceIp: "127.0.0.1",
          user: null,
          userAgent: null,
          userArn: null,
        },
        path: "/",
        protocol: "http",
        requestId: "",
        requestTimeEpoch: new Date().valueOf(),
        resourceId: "",
        resourcePath: "",
        stage: "latest",
      },
      resource: "payment",
      stageVariables: {},
    };
  },
};
